language: "node_js"
node_js: "11"

cache:
  directories:
    - "./client/node_modules"
    - "./server/node_modules"

services:
  - redis-server

jobs:
  include:
    # Install and Build
    - stage: "Build"
      name: "install"
      script:
        - npm ci
    -
      name: "build"
      script:
        - npm run build
    # Lint and Test
    - stage: "Test"
      script:
        - npm run test
    - stage: "Deploy"
      if: branch = master
      script:
        - npm run deploy

notifications:
  email: false
