language: "node_js"
node_js: "11"

cache:
  directories:
    - "./client/node_modules"
    - "./server/node_modules"

services:
  - redis-server

jobs:
  include:
    # Build
    - stage: "Build"
      script:
        - npm run build
    # Lint and Test
    - stage: "Test"
      script:
        - npm run test
    - stage: "Deploy"
      if: branch = master && type == push
      script:
        - npm run deploy

notifications:
  email: false
